### ISSUE TITLE
Shipwright: ERROR: failed to export: determining entrypoint: tried to set web to default but it doesn't exist

### ISSUE THREAD

**Issue by cmoulliard** [redhat-buildpacks/testing#12]
## Issue

During the execution of task/phase exporter using lifecycle 1.16
```
args:
  - '-app=/workspace/source/getting-started'
  - '-layers=/layers'
  - '-group=/layers/group.toml'
  - '-cache-dir=/layers/cache'
  - '-cache-image='
  - '-report=/layers/report.toml'
  - '-process-type=web'
  - '-uid=1000'
  - '-gid=1000'
  - '-stack=/layers/stack.toml'
  - kind-registry.local:5000/quarkus-hello
command:
  - /cnb/lifecycle/exporter
env:
  - name: CNB_PLATFORM_API
    value: '0.11'
image: buildpacksio/lifecycle:0.16.3
imagePullPolicy: Always
name: export
resources: {}
volumeMounts:
  - mountPath: /layers
    name: layers-dir
  - mountPath: /tmp/cache
    name: cache-dir
```
we git the following error
```
Reusing layers from image 'kind-registry.local:5000/quarkus-hello@sha256:c59abe1d8a31df35f8bdd9bf1a7d105c00aed8fe123efe9fd81f1d5e3b032a89'
no stack metadata found at path '/layers/stack.toml'
Reusing layer 'paketo-buildpacks/ca-certificates:helper'
Reusing layer 'paketo-buildpacks/bellsoft-liberica:helper'
Reusing layer 'paketo-buildpacks/bellsoft-liberica:java-security-properties'
Reusing layer 'paketo-buildpacks/bellsoft-liberica:jre'
Adding layer 'buildpacksio/lifecycle:launch.sbom'
Adding 1/1 app layer(s)
Reusing layer 'buildpacksio/lifecycle:launcher'
Adding layer 'buildpacksio/lifecycle:config'
Adding label 'io.buildpacks.lifecycle.metadata'
Adding label 'io.buildpacks.build.metadata'
Adding label 'io.buildpacks.project.metadata'
ERROR: failed to export: determining entrypoint: tried to set web to default but it doesn't exist
```
using this ClusterBuildStrategy definition: https://github.com/redhat-buildpacks/testing/blob/ebdf03fdad4902d99548aa43cef1e6db4a779ee9/k8s/shipwright/unsecured/clusterbuildstrategy.yml#L234-L257
