### ISSUE TITLE
Externalize the configuration to support dynamic strategies

### ISSUE THREAD

**Issue by cmoulliard** [redhat-buildpacks/testing#30]
## Todo

Externalize the matrix/strategy 

```
matrix:
    strategy:
      builder-image: [ 'paketobuildpacks/builder-jammy-tiny:0.0.175' ]
      pack_cli_version: [ 'v0.30.0-rc1' ]
```
in an extenal configuration file able in order to be able to import it in each job file
```
      matrix: ${{ fromJSON(needs.configure.outputs.matrix) }}
```
Such a feature will help us to implement a more dynamic mechanism to configure the matrix of the strategy and to avoid to declare in each job.yaml file the same key/value to be tested
