### ISSUE TITLE
shipwright job -> bash: line 2: results.APP_IMAGE_DIGEST.path: command not found

### ISSUE THREAD

**Issue by cmoulliard** [redhat-buildpacks/testing#41]
## Issue

Buildpack shipwright job reports such a bash error
```
Paketo Buildpack for Executable JAR 6.7.4
  https://github.com/paketo-buildpacks/executable-jar
  Process types:
    executable-jar: java -jar /workspace/source/getting-started/quarkus-run.jar (direct)
    task:           java -jar /workspace/source/getting-started/quarkus-run.jar (direct)
    web:            java -jar /workspace/source/getting-started/quarkus-run.jar (direct)
Timer: Builder ran for 47.714855808s and ended at 2023-08-28T16:14:52Z
...
bash: line 2: results.APP_IMAGE_DIGEST.path: command not found
```

**Comment by cmoulliard** [comment]
This problem is related to the fact that we cannot use/declare like with Tekton `results` - https://tekton.dev/docs/results/
Is there an equivalent ? @otaviof

**Comment by cmoulliard** [comment]
Adding double quotes dont help at all 
```
    - name: results
      image: docker.io/library/bash:5.1.4
      args:
        - -c
        - |
          set -e
          cat /layers/report.toml | grep "digest" | cut -d'"' -f2 | cut -d'"' -f2 | tr -d '\n' | tee "$(results.APP_IMAGE_DIGEST.path)"
      volumeMounts:
        - name: layers-dir
          mountPath: /layers
```
as bash reports
```
bash: line 2: results.APP_IMAGE_DIGEST.path: command not found
tee: : No such file or directory
```
